# Reference: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
---
name: Kubernetes namespace report
# Manually keep the action, input, and output descriptions in sync with the
# readme!
description: |
  GitHub Action to report info and logs from the current namespace.

inputs:
  namespace:
    default: ""
    description: "Emit a report for another namespace than the kubeconfig's current context."
    required: false
  pod-selector:
    default: ""
    description: "Limit pod reporting to pods with certain labels, example: `app.kubernetes.io/component notin (secret-server,boring-server)`. "
    required: false
  important-workloads:
    default: ""
    description: "Always provide logs of these workloads. Use space a separator, example: `deploy/my-deployment sts/my-statefulset`."
    required: false

# outputs:
#   my-output:
#     description: "..."
#     value: "..."

branding:
  icon: server
  color: purple

runs:
  using: "composite"
  steps:
    - name: Validate input
      shell: bash
      run: |
        exit 0

    - name: Emit namespace report
      shell: bash
      env:
        REPORT_IMPORTANT_WORKLOADS: ${{ inputs.important-workloads }}
        NAMESPACE: ${{ inputs.namespace }}
        POD_SELECTOR: ${{ inputs.pod-selector }}
      run: |
        ${{ github.action_path }}/k8s-namespace-report
