# Reference: https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
---
name: Kubernetes namespace report
description: |
  Emits a report of the current k8s cluster and the current namespace.

branding:
  icon: server
  color: purple

inputs:
  my-input:
    description: "..."
    required: false
    default: "..."

# outputs:
#   kubeconfig:
#     description: "..."
#     value: "..."

runs:
  using: "composite"
  steps:
    - name: Validate input
      shell: bash
      run: |
        exit 0

    - name: Emit namespace report
      shell: bash
      run: |
        ./k8s-namespace-report
