---
apiVersion: v1
kind: Pod
metadata:
  name: test-pending-1
  labels:
    pod-number: "1"
spec:
  # nodeSelector to ensure this pod never becomes scheduled
  nodeSelector:
    test.jupyter.org/node: no-node-has-this-label
  containers:
    - name: busybox
      image: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pending-2
  labels:
    pod-number: "2"
spec:
  # nodeSelector to ensure this pod never becomes scheduled
  nodeSelector:
    test.jupyter.org/node: no-node-has-this-label
  containers:
    - name: busybox
      image: busybox
